comments/urls.py
from django.urls import path

from . import views

app_name = 'comments'
urlpatterns = [
    path('', views.comments_index, name='index'),
    path('<int:comment_id>', views.comments_show, name='show'),
    path('create/', views.comments_create, name='create'),
    path('<int:comment_id>/update/', views.comments_update, name='update'),
    path('<int:comment_id>/delete/', views.comments_delete, name='delete'),
]

django_comment/urls.py
# from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from . import settings
from django.conf.urls.static import static
import os

urlpatterns = [
    path('comments/', include('comments.urls')),
    # path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),  # ルートURLで静的なindex.htmlを表示
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("", include(debug_toolbar.urls)))


# 開発環境での静的ファイルの配信設定
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=os.path.join(settings.BASE_DIR, 'static'))

comments/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    title = models.CharField(max_length=200)
    body = models.CharField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated_at']

comments/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('title', 'body')
        widgets = {
              'title': forms.TextInput(attrs={
              'class': 'form-control'
            }),
              'body': forms.TextInput(attrs={
              'class': 'form-control'
            }),
        }
        labels = {
            'title': 'タイトル',
            'body': '本文',
        }
    def clean(self):
        data = super().clean()
        title = data.get('title')
        body = data.get('body')
        if title is None:
            msg = "タイトルが入力されていません"
            self.add_error('title', msg)
        elif len(title) > 10:
            msg = "タイトルの最大文字数は10文字です"
            self.add_error('title', msg)
        if body is None:
            msg = "本文が入力されていません"
            self.add_error('body', msg)
        elif len(body) > 20:
            msg = "本文の最大文字数は20文字です"
            self.add_error('body', msg)

comments/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from .forms import CommentForm
from .models import Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

# Create your views here.
def paginate_queryset(request, queryset, count):
    paginator = Paginator(queryset, count)
    page = request.GET.get('page')
    try:
        page_obj = paginator.page(page)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    return page_obj

def comments_index(request):
    paginate = request.GET.get(key="paginate", default="2")
    comments_list = Comment.objects.all()
    # comments_list = Comment.objects.all().order_by('-created_at')
    page_obj = paginate_queryset(request, comments_list, paginate)
    context = {
        'comments' : page_obj.object_list,
        'page_obj': page_obj,
        'paginate': paginate,
    }
    return render(request, 'comments/index.html', context)

def comments_show(request, comment_id):
    context = {}
    comment = get_object_or_404(Comment, pk=comment_id)
    context['comment'] = comment

    # 1つ前（自身の直後に更新されたコメント）を取得する
    prev_comment = Comment.objects.filter(updated_at__gt=comment.updated_at).order_by('updated_at')
    # 1つ後（自身の直前に更新されたコメント）を取得する
    next_comment = Comment.objects.filter(updated_at__lt=comment.updated_at).order_by('-updated_at')
    if len(prev_comment) > 0:
        prev_id = prev_comment[0].id
    else:
        prev_id = False
    if len(next_comment) > 0:
        next_id = next_comment[0].id
    else:
        next_id = False
    context['prev_id'] = prev_id
    context['next_id'] = next_id

    return render(request, 'comments/show.html', context)

def comments_create(request):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment()
            comment.title = form.cleaned_data.get("title")
            comment.body = form.cleaned_data.get("body")
            comment.save()
            messages.success(request, '投稿しました')
            return redirect(reverse('comments:index'))
        else:
            # エラーメッセージをつけて返す
            context = {}
            context['page_title'] = 'コメントの投稿'
            context['form_name'] = 'コメントの投稿'
            context['button_label'] = 'コメントを投稿する'
            context['form'] = form
            return render(request, 'comments/form.html', context)
    else:
        context = {}
        context['form'] = CommentForm(
                            initial={
                                # 'title' : 'title',
                            }
                        )
        context['page_title'] = 'コメントの投稿'
        context['form_name'] = 'コメントの投稿'
        context['button_label'] = 'コメントを投稿する'
        return render(request, 'comments/form.html', context)

def comments_update(request, comment_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = get_object_or_404(Comment, pk=comment_id)
            comment.title = form.cleaned_data.get("title")
            comment.body = form.cleaned_data.get("body")
            comment.save()
            messages.success(request, '更新しました')
            return redirect(reverse('comments:index'))
        else:
            # エラーメッセージをつけて返す
            context = {}
            context['page_title'] = 'コメントの編集'
            context['form_name'] = 'コメントの編集'
            context['button_label'] = 'コメントを更新する'
            context['form'] = form
            return render(request, 'comments/form.html', context)
    else:
        context = {}
        comment = get_object_or_404(Comment, pk=comment_id)
        context['form'] = CommentForm(
                            initial={
                                'title' : comment.title,
                                'body' : comment.body,
                            }
                        )
        context['page_title'] = 'コメントの編集'
        context['form_name'] = 'コメントの編集'
        context['button_label'] = 'コメントを更新する'
        return render(request, 'comments/form.html', context)

def comments_delete(request, comment_id):
    if request.method == 'POST':
        comment = get_object_or_404(Comment, pk=comment_id)
        comment.delete()
        messages.success(request, 'コメントを削除しました')
        return redirect(reverse('comments:index'))
    else:
        context = {}
        comment = get_object_or_404(Comment, pk=comment_id)
        context['id'] = comment_id
        context['title'] = comment.title
        context['body'] = comment.body
        context['page_title'] = 'コメントの削除'
        context['form_name'] = 'コメントを削除しますか'
        context['button_label'] = 'コメントを削除する'
        return render(request, 'comments/delete_confirm.html', context)

comments/templates/base.html
{% load static %}<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    {% if messages %}
      <div class="container">
          <div>
              {% for message in messages %}
              <p class="flash_message" onclick="this.classList.add('hidden')"> {{ message }}</p>
              {% endfor %}
          </div>
      </div>
    {% endif %}
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

comments/templates/comments/comment_detail.html
{% extends "base.html" %}

{% block title %}
コメント {{ comment.id }}
{% endblock %}

{% block content %}
<div class="container">
  <h1 class="my-5">コメント {{ comment.id }}</h1>
  <div class="card mb-3">
    <div class="card-header">
      ID : {{ comment.id }}
    </div>
    <div class="card-body">
      <p class="card-text">Title : </p>
      <h5 class="card-title">{{ comment.title }}</h5>
      <p class="card-text">Body : </p>
      <p class="card-text">{{ comment.body }}</p>
    </div>
    <div class="card-footer">
      Created at : {{ comment.created_at }}<br>
      Updated at : {{ comment.updated_at }}
    </div>
  </div>
  <hr>
    <div>
      <p>
        <a href="{% url 'comments:update' comment.id %}">
          [ 編集 ]
        </a>
        <a href="{% url 'comments:delete' comment.id %}">
          [ 削除 ]
        </a>
      </p>
    </div>
</div>
{% endblock content %}

comments/templates/comments/comment_list.html
{% extends "base.html" %}

{% block title %}
コメント一覧
{% endblock %}

{% block content %}
<div class="container">
  <h1 class="my-5">コメント一覧</h1>
  {% for comment in object_list %}
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">
        <a href="{% url 'comments:show' comment.id  %}">
          {{ comment.title }}
        </a>
      </h5>
      <p class="card-text">{{ comment.body }}</p>
    </div>
  </div>
  {% endfor %}
  {% include 'simple_pagination.html' %}
  <hr>
  <div>
    <p>
      <a href="{% url 'comments:create' %}">
        新規コメントの投稿
      </a>
    </p>
  </div>
</div>
{% endblock content %}

comments/templates/comments/delete_confirm.html
{% extends "base.html" %}

{% block title %}
{{ page_title }}
{% endblock %}

{% block content %}
  <div class="container">
    <h1 class="my-5">{{ form_name }}</h1>
    <div class="card mb-3">
      <div class="card-header">
        ID : {{ id }}
      </div>
      <div class="card-body">
        <p class="card-text">Title : </p>
        <h5 class="card-title">{{ title }}</h5>
        <p class="card-text">Body : </p>
        <p class="card-text">{{ body }}</p>
      </div>
    </div>
    <form method="POST">
      {% csrf_token %}
      <button type="submit" class="btn btn-primary">{{ button_label }}</button>
    </form>
  </div>
{% endblock content %}

comments/templates/comments/form.html
{% extends 'base.html' %}

{% block title %}
{{ page_title }}
{% endblock %}

  {% block content %}
  <div class="container">
    <h1 class="my-5">{{ form_name }}</h1>
    <form method="POST">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-primary">{{ button_label }}</button>
    </form>
  </div>
  {% endblock content %}

comments/templates/comments/index.html
{% extends "base.html" %}

{% block title %}
コメント一覧
{% endblock %}

{% block content %}
<div class="container">
  <h1 class="my-5">コメント一覧</h1>
  {% for comment in comments %}
  <div class="card mb-3">
    <div class="card-body">
      <h5 class="card-title">
        <a href="{% url 'comments:show' comment.id  %}">
          {{ comment.title }}
        </a>
      </h5>
      <p class="card-text">{{ comment.body }}</p>
    </div>
  </div>
  {% endfor %}
  {% include 'simple_pagination.html' %}
  <hr>
  <div>
    <p>
      <a href="{% url 'comments:create' %}">
        新規コメントの投稿
      </a>
    </p>
  </div>
</div>
{% endblock content %}

comments/templates/comments/show.html
{% extends "base.html" %}

{% block title %}
コメント {{ comment.id }}
{% endblock %}

{% block content %}
<div class="container">
  <h1 class="my-5">コメント {{ comment.id }}</h1>
  {% include 'prev_next.html' %}
  <div class="card mb-3">
    <div class="card-header">
      ID : {{ comment.id }}
    </div>
    <div class="card-body">
      <p class="card-text">Title : </p>
      <h5 class="card-title">{{ comment.title }}</h5>
      <p class="card-text">Body : </p>
      <p class="card-text">{{ comment.body }}</p>
    </div>
    <div class="card-footer">
      Created at : {{ comment.created_at }}<br>
      Updated at : {{ comment.updated_at }}
    </div>
  </div>
  <hr>
    <div>
      <p>
        <a href="{% url 'comments:update' comment.id %}">
          [ 編集 ]
        </a>
        <a href="{% url 'comments:delete' comment.id %}">
          [ 削除 ]
        </a>
      </p>
      <p class="pull-right">
        <a href="{% url 'comments:index' %}">
          一覧ページに戻る
        </a>
      </p>
    </div>
    {% include 'prev_next.html' %}
</div>
{% endblock content %}

comments/templates/index.html
<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Python Django アプリケーション</h1>
  <p>
    <a href="comments/">comments アプリケーションへ</a>
  </p>

</body>
</html>

comments/templates/prev_next.html
<ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28">
  {% if prev_id %}
      <li class="page-item">
          <a class="page-link" href="{% url 'comments:show' prev_id %}">
              <span aria-hidden="true">«</span>
          </a>
      </li>
  {% else %}
      <li class="page-item">
          <a class="page-link disabled">
              <span aria-hidden="true">«</span>
          </a>
      </li>
  {% endif %}
  {% if next_id %}
      <li class="page-item">
          <a class="page-link" href="{% url 'comments:show' next_id %}">
              <span aria-hidden="true">»</span>
          </a>
      </li>
  {% else %}
      <li class="page-item">
          <a class="page-link disabled">
              <span aria-hidden="true">»</span>
          </a>
      </li>
  {% endif %}
</ul>

comments/templates/simple_pagination.html
<nav aria-label="Page navigation example">

  <ul class="pagination justify-content-center pagination-lg g-mt-28 g-mb-28">
      {% if page_obj.has_previous %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                  <span aria-hidden="true">«</span>
              </a>
          </li>
      {% else %}
          <li class="page-item">
              <a class="page-link disabled">
                  <span aria-hidden="true">«</span>
              </a>
          </li>
      {% endif %}
      {% if page_obj.has_next %}
          <li class="page-item">
              <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                  <span aria-hidden="true">»</span>
              </a>
          </li>
      {% else %}
          <li class="page-item">
              <a class="page-link disabled">
                  <span aria-hidden="true">»</span>
              </a>
          </li>
      {% endif %}
  </ul>
</nav>